version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./db:/app/db
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - SUPERUSER_SECURITY_KEY=mysecretkey
    restart: always
