# Generated by Django 5.1.5 on 2025-01-21 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_home', models.URLField()),
                ('data', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('strong_data', models.CharField(max_length=50)),
                ('strong_local', models.CharField(max_length=50)),
                ('class_data', models.CharField(max_length=50)),
                ('class_local', models.CharField(max_length=50)),
                ('class_adress', models.CharField(max_length=50)),
                ('txt_1', models.TextField()),
                ('txt_2', models.TextField()),
                ('txt_3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(blank=True, null=True)),
                ('title2', models.CharField(max_length=100)),
                ('title4', models.CharField(max_length=100)),
                ('title5', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.URLField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=50)),
                ('eixo', models.CharField(max_length=255)),
                ('mesa', models.TextField(blank=True, null=True)),
                ('componente', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mediaapp.schedule')),
            ],
        ),
    ]
